// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_wZoKLI0sMVT9k4uYjdUsg532Xo-xGXk',
    appId: '1:1047937615964:web:4c943a6b82f0cb93493e99',
    messagingSenderId: '1047937615964',
    projectId: 'test-64ce4',
    authDomain: 'test-64ce4.firebaseapp.com',
    storageBucket: 'test-64ce4.appspot.com',
    measurementId: 'G-7ZZWNFHN1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCg7L5dMakrUwgZvavmd8ZDJzpX_icQcc',
    appId: '1:1047937615964:android:21b8d4579c84b510493e99',
    messagingSenderId: '1047937615964',
    projectId: 'test-64ce4',
    storageBucket: 'test-64ce4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwm9cK5rsvA607JElFdQEKx9L_f2Gfr_Y',
    appId: '1:1047937615964:ios:e8a7d1a10d03b1fa493e99',
    messagingSenderId: '1047937615964',
    projectId: 'test-64ce4',
    storageBucket: 'test-64ce4.appspot.com',
    iosBundleId: 'com.example.flutterTrainingTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwm9cK5rsvA607JElFdQEKx9L_f2Gfr_Y',
    appId: '1:1047937615964:ios:e8a7d1a10d03b1fa493e99',
    messagingSenderId: '1047937615964',
    projectId: 'test-64ce4',
    storageBucket: 'test-64ce4.appspot.com',
    iosBundleId: 'com.example.flutterTrainingTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_wZoKLI0sMVT9k4uYjdUsg532Xo-xGXk',
    appId: '1:1047937615964:web:c79aa363369ad55a493e99',
    messagingSenderId: '1047937615964',
    projectId: 'test-64ce4',
    authDomain: 'test-64ce4.firebaseapp.com',
    storageBucket: 'test-64ce4.appspot.com',
    measurementId: 'G-M1L14S4RJJ',
  );
}
